import { z } from "zod";
import {
  MCP_OAUTH_SECURITY_SCHEMA_VERSION,
  MCP_TOKEN_FAILURE_MODES,
  MCP_TOKEN_LEAKAGE_SURFACES,
} from "./read-only-app-mcp-oauth-security-contracts";

const trueLiteral = z.literal(true);

export const McpOauthSecurityProofSchema = z
  .object({
    schemaVersion: z.literal(MCP_OAUTH_SECURITY_SCHEMA_VERSION),
    localProofOnly: trueLiteral,
    oauthSecurityContractsVerified: trueLiteral,
    oauthImplementationDeferredBoundaryVerified: trueLiteral,
    tokenSessionDeferredBoundaryVerified: trueLiteral,
    authMiddlewareDeferredBoundaryVerified: trueLiteral,
    remoteDeploymentDeferredBoundaryVerified: trueLiteral,
    userIdentityBoundaryVerified: trueLiteral,
    adminConsentBoundaryVerified: trueLiteral,
    orgRbacBoundaryVerified: trueLiteral,
    companyBindingBoundaryVerified: trueLiteral,
    clientCompanyKeySelectorBoundaryVerified: trueLiteral,
    scopeMinimizationBoundaryVerified: trueLiteral,
    tokenAudienceValidationBoundaryVerified: trueLiteral,
    tokenPassthroughForbiddenBoundaryVerified: trueLiteral,
    tokenFailureModeBoundaryVerified: trueLiteral,
    refreshTokenOfflineAccessBoundaryVerified: trueLiteral,
    tokenStorageRedactionBoundaryVerified: trueLiteral,
    tokenRevocationRotationBoundaryVerified: trueLiteral,
    noTokenLeakageBoundaryVerified: trueLiteral,
    publicExposureBlockedBoundaryVerified: trueLiteral,
    noRealFinanceDataBoundaryVerified: trueLiteral,
    noRouteBehaviorChange: trueLiteral,
    noRemoteMcpDeployment: trueLiteral,
    noOauthImplementation: trueLiteral,
    noTokenSessionImplementation: trueLiteral,
    noAuthMiddlewareImplementation: trueLiteral,
    noAppsSdkResourceImplementation: trueLiteral,
    noAppSubmission: trueLiteral,
    noDbQueriesAdded: trueLiteral,
    noSchemaMigrationsAdded: trueLiteral,
    noPublicAssets: trueLiteral,
    noOpenAiApiCalls: trueLiteral,
    noModelCalls: trueLiteral,
    noOpenAiClientOrKeyUsage: trueLiteral,
    noProviderCalls: trueLiteral,
    noExternalCommunications: trueLiteral,
    noSourceMutation: trueLiteral,
    noFinanceWrite: trueLiteral,
    fp0113BoundaryVerified: trueLiteral,
    fp0114AbsentOrLocalRemoteHostReadinessContractsVerified: trueLiteral,
    fp0115Absent: trueLiteral,
    fp0112RemotePublicOauthReadinessBoundaryStillVerified: trueLiteral,
    fp0111DefaultLocalDispatchWiringStillVerified: trueLiteral,
    fp0110DefaultDispatchPlanBoundaryStillVerified: trueLiteral,
    fp0109AdapterBoundaryStillVerified: trueLiteral,
    fp0107RouteAdapterBoundaryStillVerified: trueLiteral,
    fp0106ProtocolEnvelopeBoundaryStillVerified: trueLiteral,
    fp0100PublicSecurityBoundaryStillVerified: trueLiteral,
    failureModes: z.tuple([
      z.literal(MCP_TOKEN_FAILURE_MODES[0]),
      z.literal(MCP_TOKEN_FAILURE_MODES[1]),
      z.literal(MCP_TOKEN_FAILURE_MODES[2]),
      z.literal(MCP_TOKEN_FAILURE_MODES[3]),
      z.literal(MCP_TOKEN_FAILURE_MODES[4]),
      z.literal(MCP_TOKEN_FAILURE_MODES[5]),
    ]),
    noTokenLeakageSurfaces: z.tuple([
      z.literal(MCP_TOKEN_LEAKAGE_SURFACES[0]),
      z.literal(MCP_TOKEN_LEAKAGE_SURFACES[1]),
      z.literal(MCP_TOKEN_LEAKAGE_SURFACES[2]),
      z.literal(MCP_TOKEN_LEAKAGE_SURFACES[3]),
      z.literal(MCP_TOKEN_LEAKAGE_SURFACES[4]),
      z.literal(MCP_TOKEN_LEAKAGE_SURFACES[5]),
      z.literal(MCP_TOKEN_LEAKAGE_SURFACES[6]),
    ]),
  })
  .strict();

export type McpOauthSecurityProof = z.infer<typeof McpOauthSecurityProofSchema>;
