import { z } from "zod";
import {
  MCP_TOOL_ALLOWLIST,
  READ_ONLY_APP_MCP_SCHEMA_VERSION,
} from "./read-only-app-mcp-boundaries";

const trueLiteral = z.literal(true);

export const APP_FORBIDDEN_TOOL_PROOF_CANDIDATES = [
  "send_report",
  "release-report",
  "circulate report",
  "approve memo",
  "upload source",
  "rewrite_source",
  "write ledger",
  "post journal entry",
  "call provider",
  "deploy public app",
  "remote MCP deployment",
  "create endpoint",
  "OAuth connect",
  "submit to OpenAI",
  "customer contact",
  "pay vendor",
  "file tax return",
  "legal opinion",
  "audit opinion",
  "finance advice",
  "autonomous action",
] as const;

export const AppProofSchema = z
  .object({
    schemaVersion: z.literal(READ_ONLY_APP_MCP_SCHEMA_VERSION),
    localProofOnly: trueLiteral,
    noProductRuntime: trueLiteral,
    noPublicChatGptApp: trueLiteral,
    noRemoteMcpDeployment: trueLiteral,
    noMcpServerRuntime: trueLiteral,
    noAppsSdkUi: trueLiteral,
    noOauth: trueLiteral,
    noAppSubmission: trueLiteral,
    noEndpointsAdded: trueLiteral,
    noRoutesAdded: trueLiteral,
    noUiAdded: trueLiteral,
    noSchemaMigrationsAdded: trueLiteral,
    noPackageScriptsAdded: trueLiteral,
    noSmokeAliasesAdded: trueLiteral,
    noEvalDatasetsAdded: trueLiteral,
    noFixturesAdded: trueLiteral,
    noSampleDataAdded: trueLiteral,
    noPublicDemoDataAdded: trueLiteral,
    noPublicSourcePacksAdded: trueLiteral,
    noSourcePackMutation: trueLiteral,
    noOpenAiApiCalls: trueLiteral,
    noModelCalls: trueLiteral,
    noHostedTools: trueLiteral,
    noVectorFileSearch: trueLiteral,
    noOcr: trueLiteral,
    noPageIndex: trueLiteral,
    noProviderCalls: trueLiteral,
    noCertification: trueLiteral,
    noDelivery: trueLiteral,
    noDeployment: trueLiteral,
    noExternalCommunications: trueLiteral,
    noReportRelease: trueLiteral,
    noReportCirculation: trueLiteral,
    noApproval: trueLiteral,
    noPaymentInstruction: trueLiteral,
    noCustomerContact: trueLiteral,
    noLegalAdvice: trueLiteral,
    noAuditOpinion: trueLiteral,
    noTaxFiling: trueLiteral,
    noSourceMutation: trueLiteral,
    noFinanceWrite: trueLiteral,
    noGeneratedAdvice: trueLiteral,
    noGeneratedProductProse: trueLiteral,
    noRuntimeCodex: trueLiteral,
    noAutonomousAction: trueLiteral,
    readOnlyChatGptAppPlanVerified: trueLiteral,
    readOnlyMcpServerPlanVerified: trueLiteral,
    mcpToolAllowlistExactVerified: trueLiteral,
    mcpForbiddenToolsVerified: trueLiteral,
    appEvidenceQueryVerified: trueLiteral,
    appEvidenceFetchVerified: trueLiteral,
    appSourceCoverageFetchVerified: trueLiteral,
    appCapabilityBoundaryFetchVerified: trueLiteral,
    appRefusalPostureVerified: trueLiteral,
    promptInjectionBoundaryVerified: trueLiteral,
    privacyBoundaryVerified: trueLiteral,
    noRuntimeBoundaryVerified: trueLiteral,
    oauthDeferredBoundaryVerified: trueLiteral,
    submissionDeferredBoundaryVerified: trueLiteral,
    providerCertificationDeferredBoundaryVerified: trueLiteral,
    proofPlanVerified: trueLiteral,
    threatModelQuestionsVerified: trueLiteral,
    evidenceFreshnessLimitationsPermittedActionCitationFieldsVerified:
      trueLiteral,
    responseRefusalPostureForbiddenActionsFieldsVerified: trueLiteral,
    missingCitationRefusalVerified: trueLiteral,
    unsupportedEvidenceRefusalVerified: trueLiteral,
    staleEvidenceRefusalVerified: trueLiteral,
    unsafeActionRefusalVerified: trueLiteral,
    dataExfiltrationRefusalVerified: trueLiteral,
    rawFullFileDumpRefusalVerified: trueLiteral,
    safeDemoDataPolicyInheritedVerified: trueLiteral,
    noRealFinanceDataPostureVerified: trueLiteral,
    fp0087DocsOnlyBoundaryVerified: trueLiteral,
    fp0088Absent: trueLiteral,
    allowedTools: z.tuple([
      z.literal(MCP_TOOL_ALLOWLIST[0]),
      z.literal(MCP_TOOL_ALLOWLIST[1]),
      z.literal(MCP_TOOL_ALLOWLIST[2]),
      z.literal(MCP_TOOL_ALLOWLIST[3]),
      z.literal(MCP_TOOL_ALLOWLIST[4]),
      z.literal(MCP_TOOL_ALLOWLIST[5]),
      z.literal(MCP_TOOL_ALLOWLIST[6]),
    ]),
    forbiddenToolCandidates: z.array(z.string().min(1)).min(1),
    refusalReasons: z.array(z.string().min(1)).min(1),
    threatModelQuestionCount: z.number().int().positive(),
  })
  .strict();

export type AppProof = z.infer<typeof AppProofSchema>;
