import { z } from "zod";
import {
  MCP_REMOTE_HOST_FORBIDDEN_EXPOSURE_CATEGORIES,
  MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES,
  MCP_REMOTE_HOST_READINESS_SCHEMA_VERSION,
} from "./read-only-app-mcp-remote-host-readiness-contracts";

const trueLiteral = z.literal(true);

export const McpRemoteHostReadinessProofSchema = z
  .object({
    schemaVersion: z.literal(MCP_REMOTE_HOST_READINESS_SCHEMA_VERSION),
    localProofOnly: trueLiteral,
    remoteHostReadinessContractsVerified: trueLiteral,
    remoteDeploymentDeferredBoundaryVerified: trueLiteral,
    remoteHostInventoryBoundaryVerified: trueLiteral,
    canonicalResourceUriBoundaryVerified: trueLiteral,
    remoteMcpPathBoundaryVerified: trueLiteral,
    httpsTlsFutureRequirementBoundaryVerified: trueLiteral,
    streamableHttpTransportBoundaryVerified: trueLiteral,
    getSseDeferredBoundaryVerified: trueLiteral,
    originValidationBoundaryVerified: trueLiteral,
    corsPolicyBoundaryVerified: trueLiteral,
    cspResourcePolicyBoundaryVerified: trueLiteral,
    rateLimitAbuseControlBoundaryVerified: trueLiteral,
    loggingRedactionBoundaryVerified: trueLiteral,
    observabilityAuditCorrelationBoundaryVerified: trueLiteral,
    rollbackIncidentResponseBoundaryVerified: trueLiteral,
    healthReadinessDeferredBoundaryVerified: trueLiteral,
    noRealFinanceDataPublicDemoBoundaryVerified: trueLiteral,
    oauthSecurityPrerequisiteBoundaryVerified: trueLiteral,
    noRemoteRuntimeBoundaryVerified: trueLiteral,
    noRouteBehaviorChange: trueLiteral,
    noNewRoutePath: trueLiteral,
    noRemoteMcpDeployment: trueLiteral,
    noOauthImplementation: trueLiteral,
    noTokenSessionImplementation: trueLiteral,
    noAuthMiddlewareImplementation: trueLiteral,
    noAppsSdkResourceImplementation: trueLiteral,
    noAppSubmission: trueLiteral,
    noDbQueriesAdded: trueLiteral,
    noSchemaMigrationsAdded: trueLiteral,
    noPackageScriptsAdded: trueLiteral,
    noPublicAssets: trueLiteral,
    noOpenAiApiCalls: trueLiteral,
    noModelCalls: trueLiteral,
    noOpenAiClientOrKeyUsage: trueLiteral,
    noProviderCalls: trueLiteral,
    noExternalCommunications: trueLiteral,
    noSourceMutation: trueLiteral,
    noFinanceWrite: trueLiteral,
    fp0114BoundaryVerified: trueLiteral,
    fp0114AbsentOrLocalRemoteHostReadinessContractsVerified: trueLiteral,
    fp0115Absent: trueLiteral,
    remoteHostReadinessContractsFoundationVerified: trueLiteral,
    noRouteBehaviorChangeFromFp0114: trueLiteral,
    noNewRoutePathFromFp0114: trueLiteral,
    noRemoteMcpDeploymentFromFp0114: trueLiteral,
    noDeploymentConfigFromFp0114: trueLiteral,
    noOauthImplementationFromFp0114: trueLiteral,
    noTokenSessionImplementationFromFp0114: trueLiteral,
    noAuthMiddlewareImplementationFromFp0114: trueLiteral,
    noAppsSdkResourceFromFp0114: trueLiteral,
    noAppSubmissionFromFp0114: trueLiteral,
    noDbQueriesFromFp0114: trueLiteral,
    noSchemaMigrationsFromFp0114: trueLiteral,
    noPackageScriptsFromFp0114: trueLiteral,
    noOpenAiApiCallsFromFp0114: trueLiteral,
    noProviderExternalCallsFromFp0114: trueLiteral,
    noSourceMutationFinanceWriteFromFp0114: trueLiteral,
    noPublicAssetsSubmissionArtifactsFromFp0114: trueLiteral,
    fp0113OauthSecurityBoundaryStillVerified: trueLiteral,
    fp0112RemotePublicOauthReadinessBoundaryStillVerified: trueLiteral,
    fp0111DefaultLocalDispatchWiringStillVerified: trueLiteral,
    fp0110DefaultDispatchPlanBoundaryStillVerified: trueLiteral,
    fp0109AdapterBoundaryStillVerified: trueLiteral,
    fp0108DispatchContractsStillVerified: trueLiteral,
    fp0107RouteAdapterBoundaryStillVerified: trueLiteral,
    fp0106ProtocolEnvelopeBoundaryStillVerified: trueLiteral,
    fp0100PublicSecurityBoundaryStillVerified: trueLiteral,
    forbiddenLogCategories: z.tuple([
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[0]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[1]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[2]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[3]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[4]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[5]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[6]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[7]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[8]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[9]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[10]),
      z.literal(MCP_REMOTE_HOST_LOG_REDACTION_CATEGORIES[11]),
    ]),
    forbiddenExposureCategories: z.tuple([
      z.literal(MCP_REMOTE_HOST_FORBIDDEN_EXPOSURE_CATEGORIES[0]),
      z.literal(MCP_REMOTE_HOST_FORBIDDEN_EXPOSURE_CATEGORIES[1]),
      z.literal(MCP_REMOTE_HOST_FORBIDDEN_EXPOSURE_CATEGORIES[2]),
      z.literal(MCP_REMOTE_HOST_FORBIDDEN_EXPOSURE_CATEGORIES[3]),
      z.literal(MCP_REMOTE_HOST_FORBIDDEN_EXPOSURE_CATEGORIES[4]),
    ]),
  })
  .strict();

export type McpRemoteHostReadinessProof = z.infer<
  typeof McpRemoteHostReadinessProofSchema
>;
