import { z } from "zod";
import {
  MCP_TOOL_ALLOWLIST,
  READ_ONLY_APP_MCP_SCHEMA_VERSION,
} from "./read-only-app-mcp-boundaries";

const trueLiteral = z.literal(true);

export const APP_FORBIDDEN_TOOL_PROOF_CANDIDATES = [
  "create_mission",
  "upload_source",
  "update_ledger",
  "send_report",
  "provider_connect",
  "certify_close",
  "contact_customer",
  "approve",
  "approve this",
  "approve report",
  "delete source",
  "delete evidence",
  "delete source pack",
  "submit app",
  "app submission",
  "connect provider",
  "release-report",
  "circulate report",
  "approve memo",
  "upload source",
  "rewrite_source",
  "write ledger",
  "post journal entry",
  "call provider",
  "deploy public app",
  "remote MCP deployment",
  "create endpoint",
  "OAuth connect",
  "submit to OpenAI",
  "customer contact",
  "certify this close",
  "send to customer",
  "pay invoice",
  "pay vendor",
  "file tax return",
  "legal opinion",
  "audit opinion",
  "finance advice",
  "autonomous action",
] as const;

export const AppProofSchema = z
  .object({
    schemaVersion: z.literal(READ_ONLY_APP_MCP_SCHEMA_VERSION),
    localProofOnly: trueLiteral,
    noProductRuntime: trueLiteral,
    noPublicChatGptApp: trueLiteral,
    noRemoteMcpDeployment: trueLiteral,
    noMcpServerRuntime: trueLiteral,
    noAppsSdkUi: trueLiteral,
    noOauth: trueLiteral,
    noAppSubmission: trueLiteral,
    noEndpointsAdded: trueLiteral,
    noRoutesAdded: trueLiteral,
    noUiAdded: trueLiteral,
    noSchemaMigrationsAdded: trueLiteral,
    noPackageScriptsAdded: trueLiteral,
    noSmokeAliasesAdded: trueLiteral,
    noEvalDatasetsAdded: trueLiteral,
    noFixturesAdded: trueLiteral,
    noSampleDataAdded: trueLiteral,
    noPublicDemoDataAdded: trueLiteral,
    noPublicSourcePacksAdded: trueLiteral,
    noSourcePackMutation: trueLiteral,
    noOpenAiApiCalls: trueLiteral,
    noModelCalls: trueLiteral,
    noHostedTools: trueLiteral,
    noVectorFileSearch: trueLiteral,
    noOcr: trueLiteral,
    noPageIndex: trueLiteral,
    noProviderCalls: trueLiteral,
    noCertification: trueLiteral,
    noDelivery: trueLiteral,
    noDeployment: trueLiteral,
    noExternalCommunications: trueLiteral,
    noReportRelease: trueLiteral,
    noReportCirculation: trueLiteral,
    noApproval: trueLiteral,
    noPaymentInstruction: trueLiteral,
    noCustomerContact: trueLiteral,
    noLegalAdvice: trueLiteral,
    noAuditOpinion: trueLiteral,
    noTaxFiling: trueLiteral,
    noSourceMutation: trueLiteral,
    noFinanceWrite: trueLiteral,
    noGeneratedAdvice: trueLiteral,
    noGeneratedProductProse: trueLiteral,
    noRuntimeCodex: trueLiteral,
    noAutonomousAction: trueLiteral,
    readOnlyChatGptAppPlanVerified: trueLiteral,
    readOnlyMcpServerPlanVerified: trueLiteral,
    mcpToolAllowlistExactVerified: trueLiteral,
    mcpForbiddenToolsVerified: trueLiteral,
    appEvidenceQueryVerified: trueLiteral,
    appEvidenceFetchVerified: trueLiteral,
    appSourceCoverageFetchVerified: trueLiteral,
    appCapabilityBoundaryFetchVerified: trueLiteral,
    sourceCoverageResponseRequiredFieldsVerified: trueLiteral,
    capabilityBoundaryResponseRequiredFieldsVerified: trueLiteral,
    appRefusalPostureVerified: trueLiteral,
    promptInjectionBoundaryVerified: trueLiteral,
    privacyBoundaryVerified: trueLiteral,
    noRuntimeBoundaryVerified: trueLiteral,
    oauthDeferredBoundaryVerified: trueLiteral,
    submissionDeferredBoundaryVerified: trueLiteral,
    providerCertificationDeferredBoundaryVerified: trueLiteral,
    proofPlanVerified: trueLiteral,
    threatModelQuestionsVerified: trueLiteral,
    evidenceFreshnessLimitationsPermittedActionCitationFieldsVerified:
      trueLiteral,
    responseRefusalPostureForbiddenActionsFieldsVerified: trueLiteral,
    appMcpUnknownKeysRejected: trueLiteral,
    mcpToolAllowlistDuplicatesRejected: trueLiteral,
    mcpToolAllowlistMissingRejected: trueLiteral,
    mcpToolAllowlistReorderRejected: trueLiteral,
    mcpToolAllowlistExtraRejected: trueLiteral,
    mcpDynamicToolsRejected: trueLiteral,
    naturalLanguageForbiddenToolsVerified: trueLiteral,
    promptInjectionStringsInertDataVerified: trueLiteral,
    rawFullFileDumpAndDataExfiltrationRefusalVerified: trueLiteral,
    fp0087TypedBoundaryVerified: trueLiteral,
    missingCitationRefusalVerified: trueLiteral,
    unsupportedEvidenceRefusalVerified: trueLiteral,
    staleEvidenceRefusalVerified: trueLiteral,
    unsafeActionRefusalVerified: trueLiteral,
    dataExfiltrationRefusalVerified: trueLiteral,
    rawFullFileDumpRefusalVerified: trueLiteral,
    safeDemoDataPolicyInheritedVerified: trueLiteral,
    noRealFinanceDataPostureVerified: trueLiteral,
    fp0087DocsOnlyBoundaryVerified: trueLiteral,
    fp0088AbsentOrDocsOnlyBoundaryVerified: trueLiteral,
    fp0089AbsentOrDocsOnlyBoundaryVerified: trueLiteral,
    fp0090AbsentOrDocsOnlyBoundaryVerified: trueLiteral,
    fp0091AbsentOrLocalUiComponentBoundaryVerified: trueLiteral,
    fp0092AbsentOrLocalUiCompositionAccessibilityBoundaryVerified: trueLiteral,
    fp0093AbsentOrDocsOnlyPreviewRouteBoundaryVerified: trueLiteral,
    fp0094AbsentOrLocalPreviewRouteBoundaryVerified: trueLiteral,
    fp0095AbsentOrDocsOnlyPreviewRouteStateMatrixBoundaryVerified: trueLiteral,
    fp0096AbsentOrLocalPreviewRouteStateMatrixBoundaryVerified: trueLiteral,
    fp0097AbsentOrLocalPreviewRouteVisualQaBoundaryVerified: trueLiteral,
    fp0098AbsentOrDocsOnlyPublicAppReadinessBoundaryVerified: trueLiteral,
    fp0099AbsentOrDocsOnlyPublicAppSecurityThreatModelBoundaryVerified:
      trueLiteral,
    fp0100Absent: trueLiteral,
    publicAppReadinessPlanBoundaryVerified: trueLiteral,
    noPublicAppImplementationFromFp0098: trueLiteral,
    noAppsSdkIframeFromFp0098: trueLiteral,
    noRemoteMcpDeploymentFromFp0098: trueLiteral,
    noEndpointOauthSubmissionFromFp0098: trueLiteral,
    noOpenAiApiCallsFromFp0098: trueLiteral,
    noSourceMutationFinanceWriteFromFp0098: trueLiteral,
    noScreenshotListingSubmissionAssetsFromFp0098: trueLiteral,
    publicAppSecurityThreatModelPlanBoundaryVerified: trueLiteral,
    noEndpointImplementationFromFp0099: trueLiteral,
    noOauthImplementationFromFp0099: trueLiteral,
    noRemoteMcpDeploymentFromFp0099: trueLiteral,
    noAppsSdkResourceFromFp0099: trueLiteral,
    noAppSubmissionFromFp0099: trueLiteral,
    noOpenAiApiCallsFromFp0099: trueLiteral,
    noSourceMutationFinanceWriteFromFp0099: trueLiteral,
    noPublicAssetsSubmissionArtifactsFromFp0099: trueLiteral,
    premiumUiSecurityPlanBoundaryVerified: trueLiteral,
    premiumUiDesignSystemPlanBoundaryVerified: trueLiteral,
    premiumUiImplementationPlanBoundaryVerified: trueLiteral,
    premiumUiComponentFoundationVerified: trueLiteral,
    premiumUiCompositionAccessibilityFoundationVerified: trueLiteral,
    localUiPreviewRoutePlanBoundaryVerified: trueLiteral,
    localPreviewRouteFoundationVerified: trueLiteral,
    localPreviewRouteStateMatrixPlanBoundaryVerified: trueLiteral,
    localPreviewRouteStateMatrixFoundationVerified: trueLiteral,
    localPreviewRouteVisualQaFoundationVerified: trueLiteral,
    noUiImplementationFromFp0088: trueLiteral,
    noUiImplementationFromFp0089: trueLiteral,
    noAppsSdkIframeFromFp0089: trueLiteral,
    noUiCodeFromFp0090: trueLiteral,
    noAppsSdkIframeFromFp0090: trueLiteral,
    noEndpointOauthSubmissionFromFp0088: trueLiteral,
    noEndpointOauthSubmissionFromFp0089: trueLiteral,
    noEndpointOauthSubmissionFromFp0090: trueLiteral,
    noPublicAppImplementationFromFp0090: trueLiteral,
    noRoutesFromFp0091: trueLiteral,
    noEndpointsFromFp0091: trueLiteral,
    noAppsSdkIframeFromFp0091: trueLiteral,
    noOauthSubmissionFromFp0091: trueLiteral,
    noPublicAppImplementationFromFp0091: trueLiteral,
    noOpenAiApiCallsFromFp0091: trueLiteral,
    noSourceMutationFinanceWriteFromFp0091: trueLiteral,
    noRoutesFromFp0092: trueLiteral,
    noEndpointsFromFp0092: trueLiteral,
    noAppsSdkIframeFromFp0092: trueLiteral,
    noOauthSubmissionFromFp0092: trueLiteral,
    noPublicAppImplementationFromFp0092: trueLiteral,
    noOpenAiApiCallsFromFp0092: trueLiteral,
    noSourceMutationFinanceWriteFromFp0092: trueLiteral,
    noRouteImplementationFromFp0093: trueLiteral,
    noEndpointOauthSubmissionFromFp0093: trueLiteral,
    noPublicAppImplementationFromFp0093: trueLiteral,
    noAppsSdkIframeFromFp0093: trueLiteral,
    noOpenAiApiModelCallsFromFp0093: trueLiteral,
    noSourceMutationFinanceWriteFromFp0093: trueLiteral,
    noGeneratedProductProseRuntimeCodexFromFp0093: trueLiteral,
    noApiRoutesFromFp0094: trueLiteral,
    noBackendRoutesFromFp0094: trueLiteral,
    noEndpointsFromFp0094: trueLiteral,
    noAppsSdkIframeFromFp0094: trueLiteral,
    noOauthSubmissionFromFp0094: trueLiteral,
    noPublicAppImplementationFromFp0094: trueLiteral,
    noOpenAiApiCallsFromFp0094: trueLiteral,
    noSourceMutationFinanceWriteFromFp0094: trueLiteral,
    noRouteImplementationFromFp0095: trueLiteral,
    noScreenshotAssetsFromFp0095: trueLiteral,
    noEndpointOauthSubmissionFromFp0095: trueLiteral,
    noPublicAppImplementationFromFp0095: trueLiteral,
    noAppsSdkIframeFromFp0095: trueLiteral,
    noRemoteMcpDeploymentFromFp0095: trueLiteral,
    noOpenAiApiModelCallsFromFp0095: trueLiteral,
    noProviderCertificationDeploymentFromFp0095: trueLiteral,
    noSourceMutationFinanceWriteFromFp0095: trueLiteral,
    noGeneratedProductProseRuntimeCodexFromFp0095: trueLiteral,
    noPublicAssetsFromFp0095: trueLiteral,
    noAdditionalRoutesFromFp0096: trueLiteral,
    noApiRoutesFromFp0096: trueLiteral,
    noAppsSdkIframeFromFp0096: trueLiteral,
    noBackendRoutesFromFp0096: trueLiteral,
    noEndpointsFromFp0096: trueLiteral,
    noOauthSubmissionFromFp0096: trueLiteral,
    noOpenAiApiCallsFromFp0096: trueLiteral,
    noPublicAppImplementationFromFp0096: trueLiteral,
    noPublicAssetsFromFp0096: trueLiteral,
    noScreenshotAssetsFromFp0096: trueLiteral,
    noSourceMutationFinanceWriteFromFp0096: trueLiteral,
    noAdditionalRoutesFromFp0097: trueLiteral,
    noApiRoutesFromFp0097: trueLiteral,
    noAppsSdkIframeFromFp0097: trueLiteral,
    noBackendRoutesFromFp0097: trueLiteral,
    noEndpointsFromFp0097: trueLiteral,
    noOauthSubmissionFromFp0097: trueLiteral,
    noOpenAiApiCallsFromFp0097: trueLiteral,
    noPublicAppImplementationFromFp0097: trueLiteral,
    noPublicAssetsFromFp0097: trueLiteral,
    noScreenshotAssetsFromFp0097: trueLiteral,
    noSourceMutationFinanceWriteFromFp0097: trueLiteral,
    routeMetadataNoIndexBoundaryVerified: trueLiteral,
    screenshotlessVisualQaVerified: trueLiteral,
    accessibilityStateMatrixVerified: trueLiteral,
    allowedTools: z.tuple([
      z.literal(MCP_TOOL_ALLOWLIST[0]),
      z.literal(MCP_TOOL_ALLOWLIST[1]),
      z.literal(MCP_TOOL_ALLOWLIST[2]),
      z.literal(MCP_TOOL_ALLOWLIST[3]),
      z.literal(MCP_TOOL_ALLOWLIST[4]),
      z.literal(MCP_TOOL_ALLOWLIST[5]),
      z.literal(MCP_TOOL_ALLOWLIST[6]),
    ]),
    forbiddenToolCandidates: z.array(z.string().min(1)).min(1),
    refusalReasons: z.array(z.string().min(1)).min(1),
    threatModelQuestionCount: z.number().int().positive(),
  })
  .strict();

export type AppProof = z.infer<typeof AppProofSchema>;
